### PR TITLE
Unpromisify for old Edge like 94

### PR DESCRIPTION
**Pull request by piroor**
# Which issue(s) this PR fixes:

N/A

# What this PR does / why we need it:

It was announced that WebExtensions API on Manifest V3 addons supports Promise, but APIs don't return Promise actually on old versions like Edge 94.
Thus we need to rollback changes using Promise to using old callback style.

# How to verify the fixed issue:

Install this version and verify it is works as expected.

## The steps to verify:

1. Run `cd webextension/edge && make` to create zip file.
2. Copy ThinBridgeEdgeDev.zip to the verification environment and unzip it.
3. Install Edge 94.
4. Install policy template of Edge.
5. Start group policy editor.
6. Deactivate auto update of Edge: Administrative Templates → Microsoft Edge Update → Applications → Microsoft Edge → Update policy override → Enabled: Updates disabled
7. Install the development version via GPO, like steps described at https://gitlab.com/clear-code/browserselector/-/tree/master/#notes-for-manifest-v3
8. Create `C:\Program Files\ThinBridge\ThinBridgeBHO.ini` as:
   ```
   [Chrome]
   @BROWSER_PATH:
   @TOP_PAGE_ONLY
   @REDIRECT_PAGE_ACTION:0
   @CLOSE_TIMEOUT:3
   *://example.com/*
   
   [Default]
   @BROWSER_PATH:Edge
   @TOP_PAGE_ONLY
   @REDIRECT_PAGE_ACTION:0
   @CLOSE_TIMEOUT:3
   ```
9. Start Edge 94.
10. Open new tab and load `https://example.com/`.

## Expected result:

The tab is redirected to Chrome.

### CODE REVIEW

**Comment by piroor** [comment]
I've confirmed this change works with versions:

* Edge 94.0.992.37 (Official build) (64-bit)
* Edeg 110.0.1587.57 (Official build) (64-bit)

**Review by ashie — APPROVED** [review]

**Comment by kenhys** [comment]
In brief code review, it seems ok, but deployed development version, it causes an unexpected error and is not redirected to chrome.

Here it the screenshot to verify (https://example.com)
Web capture_28-2-2023_135423_extensions
Web capture_28-2-2023_135457_extensions
Web capture_28-2-2023_135540_settings

**Comment by piroor** [comment]
@kenhys Thanks!
I think the error around exclude group may need to be tracked as a separate issue.

**Comment by piroor** [comment]
I've tried the combination of Edge 110.0.1587.57 (Official build) (64-bit) + dev version addon + https://github.com/ThinBridge/ThinBridge/releases/tag/v4.0.2.5 and couldn't reproduce the problem @kenhys saw.
Which version of ThinBridge did you use?

**Comment by kenhys** [comment]
> Which version of ThinBridge did you use?

I've used v4.0.2.5. :thinking:

**Comment by kenhys** [comment]
Hmm, it is still reproduced.

Annotation 2023-03-01 135321
Annotation 2023-03-01 135201

**Comment by kenhys** [comment]
from chrome_debug.log:

ThinBridgeBHO.ini is fetched correctly.

```
[6488:7980:0301/141537.888:INFO:CONSOLE(97)] "Fetch config {"CloseEmptyTab":1,"OnlyMainFrame":0,"IgnoreQueryString":0,"DefaultBrowser":"Edge","Sections":[{"
Name":"chrome","Path":"","Patterns":["*://example.com/*"],"Excludes":[]}],"NamedSections":{"chrome":{"Name":"chrome","Path":"","Patterns":["*://example.com/*"],"Excludes":[]}}}", source: chrome-extension://dcojenajoibefkgdehfmnaahgnopbgcg/background.js (97)
```

But failed to handle request:

```

[7900:5868:0301/141542.636:VERBOSE1:network_delegate.cc(34)] NetworkDelegate::NotifyBeforeURLRequest: https://example.com/
[6488:7980:0301/141542.640:INFO:CONSOLE(336)] "onBeforeRequest https://example.com/ (tab=1148253850)", source: chrome-extension://dcojenajoibefkgdehfmnaahgnopbgcg/background.js (336)
[6488:7980:0301/141542.640:INFO:CONSOLE(232)] "* Lookup sections for https://example.com/", source: chrome-extension://dcojenajoibefkgdehfmnaahgnopbgcg/background.js (232)
[6488:7980:0301/141542.641:INFO:CONSOLE(240)] "handleURLAndBlock: check for section chrome ({"Name":"chrome","Path":"","Patterns":["*://example.com/*"],"Excludes":[]})", source: chrome-extension://dcojenajoibefkgdehfmnaahgnopbgcg/background.js (240)
[6488:7980:0301/141542.641:INFO:CONSOLE(0)] "Error in event handler: TypeError: section.ExcludeGroups is not iterable
    at Object.match (chrome-extension://dcojenajoibefkgdehfmnaahgnopbgcg/background.js:174:32)
    at Object.handleURLAndBlock (chrome-extension://dcojenajoibefkgdehfmnaahgnopbgcg/background.js:241:17)
    at Object.onBeforeRequest (chrome-extension://dcojenajoibefkgdehfmnaahgnopbgcg/background.js:356:14)
    at subEventCallback (extensions::webRequestEvent:1:2238)", source:  (0)
```

**Comment by piroor** [comment]
OK I've got what happens. I misunderstood the result with the latest released version of ThinBridge: it actually doesn't support `ExcludeGroups`. Yesterday I used a development build of ThinBridge with the latest source.

**Comment by piroor** [comment]
50ce889 should fix the error.

**Comment by kenhys** [comment]
> https://github.com/ThinBridge/ThinBridge/commit/50ce889d78a5f6536c052fc9df41315d86cbf4c3 should fix the error.

Verified with Edge 110.0.1587.57. redirect works as expectedly.

**Comment by piroor** [comment]
Thanks!

**Pull request merged**
